package com.mobile.ewallet.model.api.credit

data class KUMFulfillmentBody(
    var idRequest: String = "",
    var codeKewarganegaraan: String = "",
    var nomorPonsel: String = "",
    var faxArea: String = "",
    var fax: String = "",
    var codeProfesi: String = "",
    var codeJabatan: String = "",
    var codeBidangUsaha: String = "",
    var berdiriSejak: String = "",
    var bekerjaSejak: String = "",
    var codeTempatBekerja: String = "",
    var namaPerusahaan: String = "",
    var alamatKantor1: String = "",
    var alamatKantor2: String = "",
    var alamatKantor3: String = "",
    var kecamatanKantor: String = "",
    var kelurahanKantor: String = "",
    var codeKodePosKantor: String = "",
    var faxAreaKantor: String = "",
    var faxKantor: String = "",
    var telpAreaKantor: String = "",
    var telpKantor: String = "",
    var kontakDarurat: String = "",
    var codeHubungan: String = "",
    var tanggalMenikah: String = "",
    var codeDatill: String = "",
    var codeSumberDana: String = "",
    var codeKomoditas: String = "",
    var luasLahan: String = "",
    var codeJenisDebitur: String = "",
)