package com.mobile.ewallet.model.api.credit

data class KUMPrescreeningBody(
    var namaPelapor: String = "",
    var nomorKK: String = "",
    var tempatLahir: String = "",
    var codeJenisKelamin: String = "",
    var tanggalLahir: String = "",
    var codePendidikan: String = "",
    var namaIbu: String = "",
    var noTelpArea: String = "",
    var noTelp: String = "",
    var nomorKTP: String = "",
    var namaKTP: String = "",
    var alamatKTP: String = "",
    var kotaKTP: String = "",
    var kecamatanKTP: String = "",
    var kelurahanKTP: String = "",
    var codeKodePosKTP: String = "",
    var alamatRumah: String = "",
    var kotaRumah: String = "",
    var kecamatanRumah: String = "",
    var kelurahanRumah: String = "",
    var codeKodePosRumah: String = "",
    var codeDatillRumah: String = "",
    var codeStatusRumah: String = "",
    var tanggalMulaiMenempatiRumah: String = "",
    var codeStatusPernikahan: String = "",
    var namaPasangan: String = "",
    var tanggalLahirPasangan: String = "",
    var nomorKTPPasangan: String = "",
    var codeJenisKredit: String = "",
    var limitAwal: String = "",
    var codeJangkaWaktu: String = "",
    var npwp: String = "",
)